// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgoteptsgdqwnlgqdzjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnb3RlcHRzZ2Rxd25sZ3FkempnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NTk4MDgsImV4cCI6MjA5MTEzNTgwOH0.Kt7euMlb17AaT99e_sBzFjdUClXzdkw9dymOI4ws4xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});